"""Add region, concept, content, fee to quests and create schedule table

Revision ID: 6ad081c73f36
Revises: 12cc56bb580e
Create Date: 2024-02-21 22:10:55.022547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad081c73f36'
down_revision = '12cc56bb580e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('concept', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.drop_constraint('quest_manager_id_fkey', type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('quest_manager_id_fkey', 'user', ['manager_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
        batch_op.drop_column('fee')
        batch_op.drop_column('content')
        batch_op.drop_column('concept')
        batch_op.drop_column('region')

    # ### end Alembic commands ###
